In [1]:

import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [3]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [6]:
np.row_stack((a,b))

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_5452\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
matrix=np.arange(16).reshape(4,4)
matrix


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.hsplit(matrix,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [11]:
np.vsplit(matrix,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]