In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [3]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [4]:
arr1 - arr2 

array([-5, -5, -5, -5, -5])

In [5]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [6]:
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [8]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [9]:
arr2 *2

array([12, 14, 16, 18, 20])