In [1]:
import numpy as np

In [3]:
l = [2,4,6,8,10]
arr = np.array(l)
arr

array([ 2,  4,  6,  8, 10])

In [4]:
arr+10

array([12, 14, 16, 18, 20])

In [6]:
arr = np.arange(11,31).reshape(5,4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [7]:
arr + 10

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40]])

In [8]:
a = np.arange(2,9)
a

array([2, 3, 4, 5, 6, 7, 8])

In [9]:
slice = a[1:5]
slice

array([3, 4, 5, 6])

In [10]:
slice * 2

array([ 6,  8, 10, 12])

In [11]:
a

array([2, 3, 4, 5, 6, 7, 8])

In [12]:
a
b=a

In [ ]:
b[0