In [1]:
import numpy as np

In [2]:
#Columns : [Age,Math Marks,Science Marks]
data = np.array([
    [18, 85, 78],     #student 1
    [19, 92, 88],     #student 2
    [17, 76, 95],     #student 3
    [18, 65, 70],     #student 4
    [20, 90, 85]      #student 5
])

In [3]:
#Get the shape of matrix

data.shape

(5, 3)

In [4]:
#Find the average age of student

np.mean(data[:,0])

np.float64(18.4)

In [5]:
#Extract Math Marks of all students

data[:,1]

array([85, 92, 76, 65, 90])

In [7]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [8]:
#Find highest marks in Science

np.max(data[:,2])

np.int64(95)

In [16]:
#Get data of the student that has above than 90 marks in math

data[data[:,1] > 90]


array([[19, 92, 88]])

In [17]:
#Increased all maths marks by 5.

data[:,1] +5

array([90, 97, 81, 70, 95])

In [18]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [24]:
#how many student younger than 19.

len(data[data[:,0] < 19])


3

In [39]:
#Calculate the average marks in each subject(Column bise mean)

np.mean(data[:,1:],axis =0)

array([81.6, 83.2])

In [41]:
#get data of students who scored at least 80 in both subjects.

data[(data[:,1] >=80) & (data[:,2] >=80)] 

array([[19, 92, 88],
       [20, 90, 85]])

In [44]:
#Replace all science marks <75 with 0.

data[:,2][data[:,2] <75] =0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])