In [11]:
import numpy as np

In [12]:
arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
arr_slice = arr[3:10]
arr_slice

array([ 4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_slice = arr[3:10:2]
arr_slice

array([ 4,  6,  8, 10])

In [15]:
arr[8]

np.int64(9)

In [17]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [21]:
slice_2 = arr[1:4,1:3]
slice_2

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [23]:
column = arr[:,2]
column

array([ 3,  8, 13, 18, 23, 28])

In [24]:
row = arr[2,:]
row

array([11, 12, 13, 14, 15])

In [26]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])