In [1]:
import numpy as np

In [7]:
A = np.array([[1,2],[4,5]])
B = np.array([[7,8],[2,4]])

In [8]:
A

array([[1, 2],
       [4, 5]])

In [9]:
B

array([[7, 8],
       [2, 4]])

In [10]:
c = np.dot(A,B)
c


array([[11, 16],
       [38, 52]])