In [20]:
import numpy as np

In [21]:
np.random.rand(5)

array([0.32260592, 0.14914579, 0.62378918, 0.90023134, 0.23942846])

In [22]:
np.random.randn(20)

array([-0.9026169 ,  0.68209383, -1.59939879, -0.47552854, -0.01744636,
        0.68061098, -0.51502849, -0.75017067, -0.08880003, -0.71406261,
       -1.73932469, -1.8412733 ,  0.23432396,  0.32770034, -0.34914372,
       -0.75429503, -0.60551875,  1.09907179,  0.49014785, -0.19503888])

In [23]:
np.random.randint(10,20,10)

array([18, 17, 10, 15, 11, 16, 11, 17, 17, 16], dtype=int32)

In [25]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.max()

np.int64(9)

In [27]:
arr.min()

np.int64(1)

In [28]:
arr.sum()

np.int64(45)

In [30]:
np.sum(arr,axis =1)

array([ 6, 15, 24])

In [31]:
arr.mean()

np.float64(5.0)

In [32]:
arr.std()


np.float64(2.581988897471611)

In [33]:
arr.argmax()

np.int64(8)

In [34]:
arr.argmin()

np.int64(0)

RESHAPING AND RESIZEING:

In [35]:
arr = np.arange(2,20)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [43]:
arr=arr.reshape(3,6)
arr

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [45]:
arr = arr.resize(3,6)
arr

AttributeError: 'NoneType' object has no attribute 'resize'