In [3]:
import numpy as np

In [4]:
np.random.rand(5)

array([0.32721663, 0.10155917, 0.23076702, 0.07183233, 0.0398778 ])

In [5]:
np.random.randn(20)

array([-0.7818868 ,  0.57330649, -0.24803199, -1.26740965, -0.29758367,
        0.01796277, -1.20627619, -0.06116498,  0.90504492, -0.76690215,
       -0.61569997,  0.67454161, -0.32725288,  0.46083479, -0.40949825,
        1.84025596, -1.50953896, -2.1496654 , -0.5155696 , -0.09039147])

In [6]:
np.random.randint(10,20,10)

array([16, 12, 17, 11, 17, 15, 12, 18, 15, 16], dtype=int32)

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.max()

np.int64(9)

In [9]:
arr.min()

np.int64(1)

In [10]:
arr.sum()

np.int64(45)

In [11]:
np.sum(arr,axis =1)

array([ 6, 15, 24])

In [12]:
arr.mean()

np.float64(5.0)

In [13]:
arr.std()


np.float64(2.581988897471611)

In [14]:
arr.argmax()

np.int64(8)

In [15]:
arr.argmin()

np.int64(0)

RESHAPING AND RESIZEING:

In [16]:
arr = np.arange(2,20)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
arr=arr.reshape(3,6)
arr

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [32]:
arr2 = np.arange(3,28)
arr2


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [34]:
arr2 = arr2.reshape(5,5)
arr2

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])